### ISSUE TITLE
Slideshow?

### ISSUE THREAD

**Issue by Hywan** [ruuk/plugin.image.flickr#4]
Hello :-),

Thanks for this awesome job! Is it possible to start a slideshow?

**Comment by Razzeee** [comment]
I don't know if a slideshow is possible but a slideshow sceensaver is, if you install the slideshow screensaver. Can't check how its named right now.

**Comment by Hywan** [comment]
Ah cool. Will try it soon!

**Comment by Razzeee** [comment]
https://github.com/ruuk/screensaver.plugin.slideshow

**Comment by Hywan** [comment]
Perfect.

**Comment by Hywan** [comment]
How to star it?

**Comment by Razzeee** [comment]
Just set it as your screensaver in the settings, on setting up flickr just read here http://forum.kodi.tv/showthread.php?tid=153057

**Comment by Hywan** [comment]
Awesome. Thanks!

**Comment by ruuk** [comment]
Also, Kodi has the slideshow ability built in. At least in confluence, you can open the context menu and select "Start slideshow here" or from the left slide-out, there is a slideshow and a recursive slideshow option.
