### ISSUE TITLE
Certificate Failure

### ISSUE THREAD

**Issue by pjfdirect** [ruuk/plugin.image.flickr#6]
```
Using Release Kodi x32 build (version for Raspberry Pi)
Kodi compiled Feb 17 2017 by GCC 6.2.0 for Linux ARM 32-bit version 4.9.8 (264456)
Running on LibreELEC (official) - Version: 8.0.0, kernel: Linux ARM 32-bit version 4.9.8
```
The problem manifested when I tried to run my first search - for `petertheta` - after install. The reply was:

`URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED]`

Here's the log. The action seems to start at `12:47:04.980`.
http://sprunge.us/afOW

**Comment by ruuk** [comment]
I'm closing this out because I can't duplicate it and I can't access the log (which of course is my fault since it is about exactly a year since you opened this). Anyway, I apologize for taking so long to look at this. Please feel free to re-open this issue if you want to share a new log. Thanks.

**Comment by pjfdirect** [comment]
Better late than never I guess 🕚 I'll give it another go in the next few days.
